const STORE_TYPE = 'signIn';

export const SIGN_IN_CHECK = `${STORE_TYPE}/SIGN_IN_CHECK`;
export const SIGN_IN_REQUEST = `${STORE_TYPE}/SIGN_IN_REQUEST`;
export const SIGN_IN_SUCCESS = `${STORE_TYPE}/SIGN_IN_SUCCESS`;
export const SIGN_IN_FAILURE = `${STORE_TYPE}/SIGN_IN_FAILURE`;
export const SIGN_OUT = `${STORE_TYPE}/SIGN_OUT`;
